version: "3.8"
services:
    main:
        container_name: Serve
        build:
            args:
                user: laravel
                uid: 1000
            context: .
            dockerfile: Dockerfile
        command: "php artisan serve --host=0.0.0.0"
        volumes:
            - .:/app
        ports:
            - 8001:80
        networks:
            default:
                aliases:
                    - tenant.test

    db:
        platform: linux/x86_64
        image: mysql:8.0
        container_name: Database
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            # MYSQL_USER: "${DB_USERNAME}"
            MYSQL_ROOT: "root"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - db:/var/lib/mysql
        ports:
            - 3308:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.1.1
        container_name: PhpMyAdmin
        links:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        ports:
            - 8082:80

networks:
    laravel-exa:
        driver: bridge

volumes:
    db:
        driver: local
